version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper-dev-pedido-processor
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - pedido-proc-net
      
  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka-dev-pedido-processor
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - pedido-proc-net

  # Banco de dados
  pedido-proc-db:
    image: mysql:8.0
    container_name: pedido-proc-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedido_db 
    ports:
      - "33065:3306"
    volumes:
      - pedido_proc_dev_data:/var/lib/mysql
    networks:
      - pedido-proc-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  pedido-processor-api:
    build: .
    container_name: pedido-processor-api-dev
    depends_on:
      pedido-proc-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pedido-proc-db:3306/pedido_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - pedido-proc-net

volumes:
  pedido_proc_dev_data:

networks:
  pedido-proc-net: