package br.com.fiap.mspedidoprocessor.core.domain;

public enum PedidoStatus {
    ABERTO,
    PAGAMENTO_APROVADO,
    PAGAMENTO_PROCESSANDO,
    PAGAMENTO_RECUSADO,
    FALHA_CLIENTE_NAOENCONTRADO,
    FALHA_CONSULTAR_CLIENTE,
    FALHA_PROCESSAR_ESTOQUE,
    FALHA_PRODUTO_NAOENCONTRADO,
    FALHA_PAGAMENTO,
    FECHADO_SEM_ESTOQUE,
    FECHADO_COM_SUCESSO,
    FECHADO_SEM_CREDITO
}
